### ISSUE TITLE
listserv access and email issue

### ISSUE THREAD

**Issue by reemTamimi** [bklynhlth/openwillis#1]
Hello! I would like to sign up for the listserv to stay up to date with new additions. I tried to access the form, but it renders that I need permission from the owner of the form. I tried to send an email to openwillis@bklynhlth.com but I receive an error that my message can't send because the email address can't be found.

**Comment by anzarabbas** [comment]
hey @reemTamimi! thanks for bringing this up and sorry about that. the listserv [link](https://docs.google.com/forms/d/e/1FAIpQLScwc7IKChfJ1Wn373Ar3zjZmxQNIVK30OGEVnrHGOjW0ie1Sg/viewform) is back up and running and so is the email address that failed for you. that being said, the issues tab will always be a great place for bugs or general issues you're running into. shoot us an email if you want to talk through the project you're using openwillis for. cheers.
