### ISSUE TITLE
Installation error on Windows

### ISSUE THREAD

**Issue by reemTamimi** [bklynhlth/openwillis#145]
I am trying to install the library on my Windows computer. I am following the instructions in the Getting Started tab of the Wiki page. When I try to install the forest library (this command: **pip install git+https://github.com/onnela-lab/forest@5b9ba664cc09ac49f58e42cce3b271aa03a41967**), I get this error: 
![Screenshot 2024-09-04 113916](https://github.com/user-attachments/assets/00ce2bb7-fe4d-4e72-8a35-fca47b0c23cf)

I also get this error when trying to install OpenWillis (using the command **pip install openwillis**):
![Screenshot 2024-09-04 114340](https://github.com/user-attachments/assets/1317b8c8-07d4-4e48-880d-398e01affd56)

I am not sure if this is an error with trying to install on a Windows OS. I have successfully installed the library on a Mac OS.

**Comment by GeorgeEfstathiadis** [comment]
It looks like you might not have Microsoft Visual C++ 14.0 or greater. First thing you should do is go to https://visualstudio.microsoft.com/visual-cpp-build-tools/ and follow the instructions to install the latest version of Microsoft Visual C++.

I would also ensure to install/update `wheel` and `setuptools` in python. Ie `pip install -U wheel setuptools`. Then try following the installation process again. Let me know if that fixes it.

**Comment by reemTamimi** [comment]
for the first error, when trying to install forest, I ran the command **conda install -c conda-forge timezonefinder**, then ran the command to install forest. Installing Microsoft Visual C++ 14.0 helped with the error I was getting upon trying to install openwillis, but you have to select the **Desktop development with C++** workload for it to properly install.

**Comment by GeorgeEfstathiadis** [comment]
That makes sense, thank you for sharing. I thus assume that you managed to successfully install openwillis and it imports properly on your windows machine?

**Comment by reemTamimi** [comment]
I have tested importing it and that works. I will continue to perform different testing and see if I can mimic the results I get on my Mac OS.

Kind regards,
Reem Tamimi

From: GeorgiosEfstathiadis ***@***.***>
Date: Wednesday, September 4, 2024 at 3:37 PM
To: bklynhlth/openwillis ***@***.***>
Cc: Reem Tamimi ***@***.***>, Author ***@***.***>
Subject: Re: [bklynhlth/openwillis] Installation error on Windows (Issue #145)
[EXTERNAL]

That makes sense, thank you for sharing. I thus assume that you managed to successfully install openwillis and it imports properly on your windows machine?
