### ISSUE TITLE
Speech transcription function - audio file error

### ISSUE THREAD

**Issue by reemTamimi** [bklynhlth/openwillis#3]
Hi!

I am working on creating a python script to test the speech transcription function. I receive an error when I attempt to run my script using a sample audio file that I recorded (Test_Recording.wav file). However, when I use a sample file downloaded from kaggle (harvard.wav file), the script runs perfectly.

The error that renders with the Test_Recording.wav file is that the script cannot run because the audio file it is reading is of NoneType, even though the file has a size in the file directory, and it plays clearly when played separately.

This is the python script that I have:
```
import openwillis as ow
j, s = ow.speech_transcription('Test_Recording.mp3')
print(s)
```
This is the link to the sample audio file from kaggle:
https://www.kaggle.com/datasets/pavanelisetty/sample-audio-files-for-speech-recognition

Github does not allow me to upload a .wav file, but this is my recording in .mp4:
https://user-images.githubusercontent.com/85123818/215599947-246a8fe4-d76a-4077-b141-2e5d0685a71e.mp4

**Comment by vjbytes102** [comment]
@reemTamimi It is an audio file format issue. The audio file you shared has 'ID3\x03' file format.

When i read the audio file, I got this error: "File format b'ID3\x03' not understood. Only 'RIFF' and 'RIFX' supported."

After converting the test audio file into correct/supported format, everything is working fine for me. 

Please find attached audio file link with correct/supported audio format for the same.

https://github.com/vjbytes102/test-repo/blob/main/Test_Recording.wav

**Comment by reemTamimi** [comment]
@vjbytes102 The script worked using the recording you sent! How did you convert the audio file into the correct format? I did it by simply changing the extension to .wav, which now that I think about, may not have been the best way to convert it.

**Comment by vjbytes102** [comment]
@reemTamimi You have two options to convert any recording to wav.

1. Using python

from os import path
from pydub import AudioSegment
# files                                                                         
src = "transcript.mp3"
dst = "test.wav"
# convert wav to mp3                                                            
sound = AudioSegment.from_mp3(src)
sound.export(dst, format="wav")

2. Command line
ffmpeg -i input.mp3 output.wav 

i will suggest to use option 1, to automate your processing pipeline.
