### ISSUE TITLE
Audio processing

### ISSUE THREAD

**Issue by KevinHoffman1** [bklynhlth/openwillis#5]
![OpenWillis Request](https://user-images.githubusercontent.com/122998754/228605466-09541ce3-f03f-40a8-8948-bde7bd4d311c.png)

I have been having difficulty running the audio portion of the OpenWillis Code. We have been able to use video processing with great success so far, but the audio continues to come up with an error no matter what we try. 

We are running the code through a virtual server, CSIC, in which the video processing works perfectly. So it is not an issue of the source files or the destination. 

Could you offer guidance on how to fix these errors.

Here is the code we are running.
![Screenshot (137)](https://user-images.githubusercontent.com/122998754/228606279-33a255dd-93eb-429d-9c7e-eff11064e28b.png)

**Comment by anzarabbas** [comment]
Hi Kevin, we'll look into this and get back to you asap.

**Comment by vjbytes102** [comment]
@KevinHoffman1 

According to the logs in the shared screenshots, the speaker diarization function is failing and thus, there is no processed audio file available to process vocal_acoustics function.

I just tested the speaker diarization function on my end, and everything is working fine. I will suggest to use this [test_audio](https://github.com/vjbytes102/test-repo/blob/main/test_audio.wav) file, (which is an audio recording of one of the videos from YouTube) to test the openwillis setup on your server. This should ensure that the openwillis script runs successfully.

I can not provide any insight on the audio you are using without looking into it. But will suggest few things
   - validating if the actual audio file is available at the location being passed as input,
   - ensuring that the audio file is not corrupted
   - maybe their is some trouble with current file format, will suggest to convert it to WAV format using Python

But give it a try with test audio file first and let me know how it goes.

**Comment by KevinHoffman1** [comment]
Thank you very much for your assistance so far. I have tried making some changes and played around a lot, and the same main diarization error occurs with using the test audio file. I have confirmed its file path and properties, and when I download the file uploaded to the server from the server, it is uncorrupted. I have it set to print the file it is passing as input and it matches exactly the file path of the video it is supposed to call.

**Comment by anzarabbas** [comment]
Thanks Kevin, let us get back to youi.

**Comment by KevinHoffman1** [comment]
![Screenshot (161)](https://user-images.githubusercontent.com/122998754/230650525-6f082aba-ebf2-4596-b740-9a9b9cd399f8.png)

**Comment by KevinHoffman1** [comment]
Above is the current code I am running for reference with only the diarization portions.  The other lines above it I tested to make certain they work.

**Comment by anzarabbas** [comment]
hi @KevinHoffman1, not sure what's going on. shoot us an email at openwillis@bklynhlth.com and we can try and troubleshoot.

**Comment by anzarabbas** [comment]
hi @KevinHoffman1, looks like the source of the error was your hftoken. Closing this issue now.
